# Generated by Django 5.1.3 on 2024-11-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
